# infrastructure/k8s/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-support-api
  labels:
    app: social-support-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-support-api
  template:
    metadata:
      labels:
        app: social-support-api
    spec:
      containers:
        - name: api
          image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/social-support-ai:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: social-support-secrets
                  key: POSTGRES_URL
            - name: CHROMA_URL
              valueFrom:
                secretKeyRef:
                  name: social-support-secrets
                  key: CHROMA_URL
            - name: LLM_HOST_URL
              valueFrom:
                secretKeyRef:
                  name: social-support-secrets
                  key: LLM_HOST_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"