apiVersion: v1
kind: Service
metadata:
  name: chromadb
  labels:
    app: chromadb
spec:
  type: ClusterIP
  selector:
    app: chromadb
  ports:
    - name: http
      port: 8000
      targetPort: 8000