# infrastructure/k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: social-support-secrets
type: Opaque
stringData:
  POSTGRES_URL: "postgresql://postgres:postgres@social-support-db:5432/social_support"
  CHROMA_URL: "http://chroma:8000"
  LLM_HOST_URL: "http://llm:11434"